services:
  bulwark:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - testapi

  testapi:
    build:
      context: .
      dockerfile: Dockerfile.testapi
    ports:
      - "9090:9090"
