services:
  bulwark:
    image: ghcr.io/stormbane-security/bulwark:dev
    ports:
      - "8080:8080"
    depends_on:
      - testapi

  testapi:
    image: ghcr.io/stormbane-security/bulwark-testapi:dev
    ports:
      - "9090:9090"
